# Nom de l'application
spring.application.name=gestion-visites-medical

# Connexion PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/centre_medical_db
spring.datasource.username=postgres
spring.datasource.password=1234

# Configuration JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Port du serveur (optionnel, 8080 par défaut)
server.port=8080